version: "3.8"

services:
  backend:
    container_name: expense-backend
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8080:8080"
    restart: always
    env_file:
      - .env